name: Qodana Detecção de Long Method

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         fetch-depth: 0

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2023.2
        with:
          # Apontar para o ficheiro XML que criou
          args: "--profile-path,long-method-thresholds.xml"
          # Quality Gate: falha se encontrar qualquer violação (Long Method > 20 LOC)
          fail-threshold: 0 
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
